package com.csapat.rooms;

public enum Tile
{
 WALL, FLOOR, DOOR_CLOSED, DOOR_OPEN, TRAPDOOR_CLOSED, TRAPDOOR_OPEN, BOSSDOOR_OPEN, BOSSDOOR_CLOSED, ITEMDOOR_OPEN,ITEMDOOR_CLOSED, SHOPDOOR_OPEN, SHOPDOOR_CLOSED;
}
